spring:
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: first-name-service
  datasource:
    url: jdbc:tracing:h2:mem:first_name?traceWithActiveSpanOnly=true
    driver-class-name: io.opentracing.contrib.jdbc.TracingDriver
server:
  port: 9091
opentracing:
  jaeger:
    udp-sender:
      host: jaeger